version: "3.8"

networks:
        queryclient:

services:
        api:
                build: 
                        dockerfile: Dockerfile_api
                        context: .
                container_name: qc_api
                restart: "always"
                ports:
                        - "50601:22"
                        - "50602:5000"
                volumes:
                        - ./restapi:/data

        database:
                image: postgres:14-bullseye
                container_name: qc_database
                environment:
                        - POSTGRES_USER=qcuser
                        - POSTGRES_PASSWORD=qcpassword
                restart: "always"
                volumes: 
                        - ./initdatabase.sql:/docker-entrypoint-initdb.d/initdhdatabases.sql
                        - db-data:/var/lib/postgresql/data
        gui:
                build:
                        dockerfile: Dockerfile_gui
                        context: .
                container_name: qc_gui
                restart: "always"
                ports:
                        - "50604:3000"
                volumes:
                        - gui-data:/data

volumes:
        db-data:
                driver: local
        gui-data:
                driver: local
