FROM node:14-bullseye-slim

# copy source code to volume
ADD ./frontend /data

# set working directory in container
WORKDIR /data

# add `/app/node_modules/.bin` to $PATH
ENV PATH ./node_modules/.bin:$PATH

# install app dependencies if necessary
RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent

# start app
CMD ["npm", "start"]
